apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
spec:
  source:
    helm:
      values: |
        replicaCount: 2
        message: patch from values as string
        service:
          port: 8080