apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
spec:
  source:
    helm:
      values:
        nameOverride: "prod-helloworld"
        fullNameOverride: "prod-helloworld"
        replicaCount: 3
        message: PROD, patch from values as raw
        service:
          type: NodePort
          port: 80