apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-apps
spec:
  project: default
  source:
    repoURL: https://github.com/mcbenjemaa/argocd-apps
    targetRevision: master
    path: overlays/qa/
  destination:
    server: https://kubernetes.default.svc
    namespace: "argocd"
